spring:
  application:
    name: datsanbong

  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:datsanbong}?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&socketTimeout=30000"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:admin}
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

minio:
  accessKey: minioadmin
  secretKey: minioadmin
  endpoint: http://localhost:9000
  bucketName: uploads

server:
  port: 8080
  servlet:
    context-path: /api/v1

